function Hd = hp_filter_acc(Fs)
%HP_FILTER_ACC Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 26-Apr-2021 10:33:28

% Butterworth Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
if ~exist('Fs', 'var')
    Fs = 25;  % Sampling Frequency
elseif isempty(Fs)
    Fs = 25;
end

Fstop = 0.1;         % Stopband Frequency
Fpass = 0.5;         % Passband Frequency
Astop = 80;          % Stopband Attenuation (dB)
Apass = 1;           % Passband Ripple (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
